#!/usr/bin/env bash
#install the ufw firewall and setup a few rules on web-01

apt-get install ufw
sudo apt install ufw
sudo apt default allow outgoing
sudo apt default deny incoming
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
ufw enable
sudo ufw status verbose
